name: cogmod_1_IAM
dependencies:
  - python=3.7.7
  - ipykernel=5.1.4
  - pandas=1.0.3
  - matplotlib=3.1.3
  - scipy=1.4.1
  - seaborn=0.10.0
  # metameric dependencies (https://github.com/clips/metameric/blob/4f7c95adf75b0a301dbd0c082969a23f845b1e9d/requirements.txt)
  # another one is "wordkit" install via pip (see below)
  - numpy=1.18.1
  - cython=0.29.17
  - flask=1.1.2
  - tqdm=4.46.0
  - setuptools=46.4.0
  - pip=20.0.2
  - pip:
    - wordkit>=2.0.0
